version: '3.7'

services: 
  app:
    build:
      context: .
    container_name: api
    restart: always
    environment: 
      - APP_NAME=RodCalc
      - HEADER_NAME=${HEADER_NAME}
      - SECRET_KEY=${SECRET_KEY}
    expose:
      - 8080 # uwsgi is listening to :8080 so expose :8080
    volumes:
      - ./app:/app # local development autorefresh without building
  
  proxy:
    build: ./proxy
    container_name: nginx
    restart: always
    ports: 
      - "8000:8000"

  client:
    build: ./client
    container_name: frontend
    environment:
      - VUE_APP_SECRET_KEY=${VUE_APP_SECRET_KEY}
    volumes:
      - './client:/client'
    restart: always
    ports:
      - "5500:5500"
